# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Set Version

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
jobs:
  tag_version:
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: Paul Murray
      GIT_AUTHOR_EMAIL: plmrry@gmail.com
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 15
    - name: Set NPM version
      uses: Reedyuk/NPM-Version@1.1.1
      with:
        version: '${{ github.event.inputs.version }}'
        git-tag-version: 'true'
    - name: Commit and push
      uses: stefanzweifel/git-auto-commit-action@v4