# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Version Bump, Release, and Publish

on: workflow_dispatch
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 15
    - run: git config --global user.email "plmrry@gmail.com"
    - run: git config --global user.name "Paul Murray"
    - run: npm version patch
  push:
    needs: version
    runs-on: ubuntu-latest
    steps:
    - run: git push
    - run: git push --tags
  release:
    needs: push
    runs-on: ubuntu-latest
    steps:
    - run: gh config set prompt disabled
    - run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
    - run: gh release create `git describe --abbrev=0`
  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
